# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DormInfo_tem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(help_text='手机号码', max_length=20, verbose_name='手机号码')),
                ('drxiaoqu', models.CharField(default='', help_text='宿舍园区', max_length=20, verbose_name='宿舍园区')),
                ('drlou', models.CharField(default='', help_text='宿舍楼', max_length=20, verbose_name='宿舍楼')),
                ('drRoomId', models.CharField(default='', help_text='房间编号', max_length=20, verbose_name='房间编号')),
            ],
            options={
                'verbose_name_plural': '用户宿舍信息临时存储',
                'verbose_name': '用户宿舍信息临时存储',
            },
        ),
        migrations.CreateModel(
            name='ElectricCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(help_text='手机号码', max_length=20, verbose_name='手机号码')),
                ('moneyLeft', models.CharField(max_length=20, verbose_name='剩余电费')),
                ('energyLeft', models.CharField(max_length=20, verbose_name='剩余电量')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
                ('message_status', models.CharField(default='1', max_length=5, null=True, verbose_name='发送短信状态')),
                ('result', models.CharField(default='1', max_length=5, null=True, verbose_name='爬取结果')),
                ('crawl_status', models.CharField(default='0', max_length=5, null=True, verbose_name='爬取信息状态')),
            ],
            options={
                'verbose_name_plural': '用户宿舍电费信息',
                'verbose_name': '用户宿舍电费信息',
            },
        ),
    ]
