# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_auto_20170928_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo_tem',
            name='drRoomId',
            field=models.CharField(help_text='房间编号，如 0105', max_length=20, verbose_name='房间编号'),
        ),
        migrations.AlterField(
            model_name='dorminfo_tem',
            name='drlou',
            field=models.CharField(help_text='宿舍楼，如 南光8', max_length=20, verbose_name='宿舍楼'),
        ),
        migrations.AlterField(
            model_name='dorminfo_tem',
            name='drxiaoqu',
            field=models.CharField(help_text='宿舍园区，如 31', max_length=20, verbose_name='宿舍园区'),
        ),
    ]
