# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentanceNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(default='NULL', max_length=10, verbose_name='1-2节课')),
                ('three', models.CharField(default='NULL', max_length=10, verbose_name='3-4节课')),
                ('five', models.CharField(default='NULL', max_length=10, verbose_name='5-6节课')),
                ('seven', models.CharField(default='NULL', max_length=10, verbose_name='7-8节课')),
                ('nine', models.CharField(default='NULL', max_length=10, verbose_name='9-10节课')),
                ('zj', models.CharField(default='NULL', max_length=10, verbose_name='增加次数')),
                ('bk', models.CharField(default='NULL', max_length=10, verbose_name='补课次数')),
                ('sum', models.CharField(default='NULL', max_length=10, verbose_name='本学期总次数')),
                ('last_sum', models.CharField(default='NULL', max_length=10, verbose_name='上学期出勤次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '出勤信息',
                'verbose_name': '出勤信息',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_pe', models.CharField(default='NULL', max_length=200, verbose_name='金教电子账号')),
                ('password_pe', models.CharField(default='NULL', max_length=200, verbose_name='金教电子密码')),
                ('status', models.CharField(default='0', max_length=50, verbose_name='账号状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '体育查询登录账户信息',
                'verbose_name': '体育查询登录账户信息',
            },
        ),
    ]
