# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountTem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_pe', models.CharField(default='NULL', max_length=200, verbose_name='金教电子账号')),
                ('password_pe', models.CharField(default='NULL', max_length=200, verbose_name='金教电子密码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '账户信息临时信息',
                'verbose_name': '账户信息临时信息',
            },
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': '金教电子账户信息', 'verbose_name_plural': '金教电子账户信息'},
        ),
    ]
