# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe', '0003_auto_20171022_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentancenum',
            name='crawl_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='crawl_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间'),
        ),
        migrations.AddField(
            model_name='useraccounttem',
            name='crawl_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间'),
        ),
    ]
