# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotice',
            name='title',
            field=models.CharField(default='NULL', max_length=100, verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='messagenotice',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
