# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_suggestion_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='image_1',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_1_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
