# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20171002_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='image_1_url',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
