# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20171002_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image_2_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图-2'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_3_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图-3'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_4_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图-4'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_5_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图-5'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='image_1_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图—1'),
        ),
    ]
