# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20171002_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='image_1_url',
            field=models.CharField(default='NULL', max_length=500, verbose_name='用户截图-1'),
        ),
    ]
