# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20171002_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLaunchImageCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NULL', max_length=200, verbose_name='图片标题')),
                ('url', models.CharField(default='', max_length=500, verbose_name='图片链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': 'APP启动页图片 - 日常',
                'verbose_name': 'APP启动页图片 - 日常',
            },
        ),
        migrations.CreateModel(
            name='AppLaunchImageLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NULL', max_length=200, verbose_name='图片标题')),
                ('url', models.CharField(default='', max_length=500, verbose_name='图片链接')),
                ('start_date', models.DateTimeField(verbose_name='开始展示日期')),
                ('end_date', models.DateTimeField(verbose_name='结束展示日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': 'APP启动页图片 - 最新',
                'verbose_name': 'APP启动页图片 - 最新',
            },
        ),
    ]
