# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_appmessagegroupnotice_jwmessagegroupnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmessagenotice',
            name='all_student',
        ),
        migrations.RemoveField(
            model_name='appmessagenotice',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='jwmessagenotice',
            name='all_student',
        ),
        migrations.RemoveField(
            model_name='jwmessagenotice',
            name='grade',
        ),
        migrations.AlterField(
            model_name='appmessagegroupnotice',
            name='all_student',
            field=models.BooleanField(default=False, help_text='若勾选，则用户年级填写NULL', verbose_name='通知所有人'),
        ),
        migrations.AlterField(
            model_name='appmessagegroupnotice',
            name='grade',
            field=models.CharField(default='NULL', help_text='一次填写一个年级，如 2015', max_length=30, null=True, verbose_name='用户年级'),
        ),
        migrations.AlterField(
            model_name='jwmessagegroupnotice',
            name='all_student',
            field=models.BooleanField(default=False, help_text='若勾选，则用户年级填写NULL', verbose_name='通知所有人'),
        ),
        migrations.AlterField(
            model_name='jwmessagegroupnotice',
            name='grade',
            field=models.CharField(default='NULL', help_text='一次填写一个年级，如 2015', max_length=30, null=True, verbose_name='用户年级'),
        ),
    ]
