# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20171112_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmessagegroupnotice',
            options={'verbose_name': '群发关于APP的消息记录', 'verbose_name_plural': '群发关于APP的消息记录'},
        ),
        migrations.AlterModelOptions(
            name='jwmessagegroupnotice',
            options={'verbose_name': '群发教务系统的消息记录', 'verbose_name_plural': '群发教务系统的消息记录'},
        ),
        migrations.RemoveField(
            model_name='jwmessagegroupnotice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='jwmessagenotice',
            name='title',
        ),
    ]
