# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20171112_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='applaunchimagecommon',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], default='iOS', max_length=20, verbose_name='使用平台'),
        ),
        migrations.AddField(
            model_name='applaunchimagecommon',
            name='size',
            field=models.CharField(choices=[('640', '640'), ('750', '750'), ('1242', '1242'), ('1125', '1125')], default='640', max_length=20, verbose_name='图片的宽度'),
        ),
        migrations.AddField(
            model_name='applaunchimagelatest',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], default='iOS', max_length=20, verbose_name='使用平台'),
        ),
        migrations.AddField(
            model_name='applaunchimagelatest',
            name='size',
            field=models.CharField(choices=[('640', '640'), ('750', '750'), ('1242', '1242'), ('1125', '1125')], default='640', max_length=20, verbose_name='图片的宽度'),
        ),
    ]
