# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20171113_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmessagenotice',
            name='read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AddField(
            model_name='jwmessagenotice',
            name='read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
