# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0015_auto_20171116_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='NULL', max_length=200, verbose_name='请求类型')),
                ('error', models.CharField(default='NULL', max_length=500, null=True, verbose_name='错误内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '客户端Bug记录',
                'verbose_name_plural': '客户端Bug记录',
            },
        ),
    ]
