# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170928_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default='NULL', max_length=30, verbose_name='教务系统的key'),
        ),
    ]
