# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170928_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='黑名单'),
        ),
    ]
