# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_app',
            field=models.CharField(default='NULL', max_length=50, verbose_name='用户APP的登录密码'),
        ),
    ]
