# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_image',
            new_name='user_image_url',
        ),
    ]
