# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171008_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo_tem_1',
            name='password_jw',
            field=models.CharField(default='NULL', max_length=200, verbose_name='教务系统密码'),
        ),
        migrations.AlterField(
            model_name='userinfo_tem_2',
            name='password_jw',
            field=models.CharField(default='NULL', max_length=200, verbose_name='教务系统密码'),
        ),
        migrations.AlterField(
            model_name='userinfo_tem_3',
            name='password_jw',
            field=models.CharField(default='NULL', max_length=200, verbose_name='教务系统密码'),
        ),
        migrations.AlterField(
            model_name='userinfo_tem_4',
            name='password_jw',
            field=models.CharField(default='NULL', max_length=200, verbose_name='教务系统密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_app',
            field=models.CharField(default='NULL', max_length=200, verbose_name='用户APP的登录密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_jw',
            field=models.CharField(default='NULL', max_length=200, verbose_name='教务系统密码'),
        ),
    ]
