# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171008_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='week_now',
            field=models.CharField(default='NULL', max_length=5, verbose_name='当前周数，配合课程表使用,0为假期'),
        ),
    ]
