# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time_app', models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间')),
                ('device_type', models.CharField(default='NULL', max_length=30, verbose_name='设备类型')),
            ],
            options={
                'verbose_name_plural': '用户登录信息',
                'verbose_name': '用户登录信息',
            },
        ),
        migrations.CreateModel(
            name='MessageNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='NULL', max_length=300, verbose_name='通知内容')),
                ('ios_version', models.CharField(default='NULL', max_length=100, null=True, verbose_name='iOS需要通知的版本')),
                ('andriod_version', models.CharField(default='NULL', max_length=100, null=True, verbose_name='Andriod需要通知的版本')),
                ('mina_version', models.CharField(default='NULL', max_length=100, null=True, verbose_name='小程序需要通知的版本')),
                ('grade', models.CharField(default='NULL', max_length=30, null=True, verbose_name='用户年级')),
                ('add_time', models.DateTimeField(auto_now=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '通知用户的最新消息',
                'verbose_name': '通知用户的最新消息',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='建议内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '用户建议',
                'verbose_name': '用户建议',
            },
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('content', models.CharField(default='', max_length=500, null=True, verbose_name='短信发送内容')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='短信发送时间')),
            ],
            options={
                'verbose_name_plural': '短信发送内容',
                'verbose_name': '短信发送内容',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '短信验证码',
                'verbose_name': '短信验证码',
            },
        ),
    ]
