# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_auto_20170929_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ios', models.CharField(default='NULL', max_length=200, verbose_name='iOS注册id')),
                ('id_android', models.CharField(default='NULL', max_length=200, verbose_name='Android注册id')),
                ('tag_grade', models.CharField(default='NULL', max_length=5, verbose_name='用户年级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
