# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_pushsettings_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsettings',
            options={'verbose_name': '极光推送信息', 'verbose_name_plural': '极光推送信息'},
        ),
    ]
