# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_auto_20171101_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='NULL', help_text='和username保持一致', max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name_plural': '删除用户信息',
                'verbose_name': '删除用户信息',
            },
        ),
    ]
