# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_userinfodelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginStatistics',
            fields=[
                ('login_date', models.DateField(primary_key=True, serialize=False, verbose_name='统计日期')),
                ('page_view', models.IntegerField(default=0, verbose_name='登录次数')),
                ('unique_visitor', models.IntegerField(default=0, verbose_name='独立访客')),
            ],
            options={
                'verbose_name': '用户登录次数统计',
                'verbose_name_plural': '用户登录次数统计',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationStatistics',
            fields=[
                ('reg_date', models.DateField(primary_key=True, serialize=False, verbose_name='统计日期')),
                ('people_number', models.IntegerField(default=0, verbose_name='注册人数')),
            ],
            options={
                'verbose_name': 'APP注册人数统计',
                'verbose_name_plural': 'APP注册人数统计',
            },
        ),
        migrations.AddField(
            model_name='logininfo',
            name='app_version',
            field=models.CharField(default='NULL', max_length=200, verbose_name='app版本'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='device_version',
            field=models.CharField(default='NULL', max_length=200, verbose_name='设备版本'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='imei',
            field=models.CharField(default='NULL', max_length=200, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='ip',
            field=models.CharField(default='NULL', max_length=200, verbose_name='用户IP'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='latitude',
            field=models.CharField(default='NULL', max_length=200, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='logininfo',
            name='longitude',
            field=models.CharField(default='NULL', max_length=200, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='device_type',
            field=models.CharField(default='NULL', max_length=200, verbose_name='设备类型'),
        ),
        migrations.AlterUniqueTogether(
            name='logininfo',
            unique_together=set([]),
        ),
    ]
