# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(default='', max_length=20, verbose_name='学生学号')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号码')),
                ('sub_id', models.CharField(default='', max_length=20, null=True, verbose_name='课程id')),
                ('term_id', models.CharField(default='', max_length=20, null=True, verbose_name='学期id')),
                ('sub_name', models.CharField(default='', max_length=100, null=True, verbose_name='课程中文名')),
                ('teacher', models.CharField(default='', max_length=20, null=True, verbose_name='老师')),
                ('weekId', models.CharField(default='', max_length=20, null=True, verbose_name='第几周')),
                ('week', models.CharField(default='', max_length=20, null=True, verbose_name='星期')),
                ('attendence_date', models.CharField(default='', max_length=20, null=True, verbose_name='缺勤日期')),
                ('attendence_type', models.CharField(default='', max_length=20, null=True, verbose_name='类型')),
                ('times', models.CharField(default='', max_length=20, null=True, verbose_name='次数/课时')),
                ('result', models.CharField(max_length=20, null=True, verbose_name='查询结果')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name_plural': '用户出勤信息',
                'verbose_name': '用户出勤信息',
            },
        ),
        migrations.CreateModel(
            name='ClassSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(default='', max_length=20, verbose_name='学生学号')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号码')),
                ('sub_id', models.CharField(default='', max_length=20, null=True, verbose_name='课程id')),
                ('class_type', models.CharField(default='', max_length=20, null=True, verbose_name='调、停、补类型')),
                ('sub_name', models.CharField(default='', max_length=100, null=True, verbose_name='课程中文名')),
                ('teacher', models.CharField(default='', max_length=20, null=True, verbose_name='老师')),
                ('date_weekId', models.CharField(default='', max_length=20, null=True, verbose_name='第几周')),
                ('date_week', models.CharField(default='', max_length=20, null=True, verbose_name='星期')),
                ('section', models.CharField(default='', max_length=20, null=True, verbose_name='节次')),
                ('date_detail', models.CharField(default='', max_length=20, null=True, verbose_name='具体日期')),
                ('classroom', models.CharField(default='', max_length=20, null=True, verbose_name='教室')),
                ('result', models.CharField(default='', max_length=20, null=True, verbose_name='结果')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name_plural': '用户调停补课信息',
                'verbose_name': '用户调停补课信息',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(default='', max_length=20, verbose_name='学生学号')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号码')),
                ('term_name', models.CharField(max_length=50, verbose_name='学期中文名')),
                ('sub_id', models.CharField(max_length=20, null=True, verbose_name='课程id')),
                ('sub_name', models.CharField(max_length=100, null=True, verbose_name='课程中文名')),
                ('credit', models.CharField(max_length=20, null=True, verbose_name='学分')),
                ('teacher', models.CharField(max_length=500, null=True, verbose_name='老师')),
                ('start_end_week', models.CharField(max_length=50, null=True, verbose_name='起终周')),
                ('method', models.CharField(max_length=20, null=True, verbose_name='上课方式')),
                ('peopleNum', models.CharField(max_length=20, null=True, verbose_name='人数')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
                ('result', models.CharField(max_length=20, null=True, verbose_name='查询结果')),
                ('week_day', models.CharField(max_length=50, null=True, verbose_name='周几')),
                ('class_range', models.CharField(max_length=50, null=True, verbose_name='第几节课-第几节课')),
                ('frequency', models.CharField(max_length=50, null=True, verbose_name='频率')),
                ('c_classroom', models.CharField(max_length=50, null=True, verbose_name='教室')),
                ('week_range', models.CharField(max_length=50, null=True, verbose_name='第几周-第几周')),
            ],
            options={
                'verbose_name_plural': '用户课表信息',
                'verbose_name': '用户课表信息',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(default='', max_length=20, verbose_name='学生学号')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号码')),
                ('exam_id', models.CharField(default='', max_length=20, null=True, verbose_name='考试id')),
                ('exam_name', models.CharField(default='', max_length=50, null=True, verbose_name='考试类型中文名')),
                ('exam_date', models.CharField(default='', max_length=50, null=True, verbose_name='考试日期')),
                ('week', models.CharField(default='', max_length=20, null=True, verbose_name='星期')),
                ('interval', models.CharField(default='', max_length=20, null=True, verbose_name='时间段')),
                ('exam_time', models.CharField(default='', max_length=20, null=True, verbose_name='具体时间')),
                ('exam_location', models.CharField(default='', max_length=20, null=True, verbose_name='地点')),
                ('exam_subject', models.CharField(default='', max_length=20, null=True, verbose_name='科目')),
                ('method', models.CharField(default='', max_length=20, null=True, verbose_name='考核方式')),
                ('status', models.CharField(default='', max_length=20, null=True, verbose_name='状态')),
                ('result', models.CharField(default='', max_length=20, null=True, verbose_name='结果')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name_plural': '用户考试安排信息',
                'verbose_name': '用户考试安排信息',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(max_length=10, verbose_name='学生学号')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号码')),
                ('term_id', models.CharField(max_length=20, null=True, verbose_name='学期id')),
                ('term_name', models.CharField(max_length=50, null=True, verbose_name='学期中文名')),
                ('sub_id', models.CharField(max_length=20, null=True, verbose_name='课程id')),
                ('sub_name', models.CharField(max_length=100, null=True, verbose_name='课程中文名')),
                ('credit', models.CharField(max_length=20, null=True, verbose_name='学分')),
                ('mark', models.CharField(max_length=20, null=True, verbose_name='分数')),
                ('method', models.CharField(max_length=20, null=True, verbose_name='修课方式')),
                ('result', models.CharField(max_length=20, null=True, verbose_name='查询结果')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name_plural': '用户成绩信息',
                'verbose_name': '用户成绩信息',
            },
        ),
        migrations.CreateModel(
            name='TermInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(default='NULL', max_length=10, verbose_name='学期id')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号码')),
                ('term_name', models.CharField(max_length=50, verbose_name='学期中文名')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name_plural': '用户学期信息',
                'verbose_name': '用户学期信息',
            },
        ),
    ]
