# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaowu', '0002_auto_20170928_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='老师'),
        ),
        migrations.AlterField(
            model_name='classswitch',
            name='teacher',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='老师'),
        ),
    ]
